### ISSUE TITLE
It just launches foot over and over

### ISSUE THREAD

**Issue by xircon** [DvdGiessen/kwin-toggleterminal#2]
```
qdbus nl.dvdgiessen.dbusapplauncher /nl/dvdgiessen/DBusAppLauncher nl.dvdgiessen.dbusapplauncher.Exec.Cmd /usr/bin/foot
```
Launches foot, so dbus service running, but does not toggle.  I get a new terminal on each key press.

**Comment by DvdGiessen** [comment]
It tries to find the terminal by [matching the window caption](https://github.com/DvdGiessen/kwin-toggleterminal/blob/3a2cb55684fd09fa52f61fdee812d1395d4dbde9/contents/code/main.js#L17-L23) to the configurable prefix and suffix.

![toggle-terminal settings window](https://github.com/DvdGiessen/kwin-toggleterminal/assets/954385/11f102ab-d25e-4381-b0e9-470661914323)

So my best guess would be that it fails to match the foot window; perhaps because it has a different caption? Note that by default the window caption may  be changed by commands running in the terminal by outputting some escape sequence, for example you can do this yourself by running `echo -e "\033]0;MyCustomTitle\007"`.

An easy way to view the captions of all your windows, be they hidden or not, is by checking the KWin debug console. To access it: Open KRunner, type ‘kwin’, and click on `Open KWin debug console`. The first tab gives you a list of all windows, expand them to check their `caption` property.

![KWin debug console showing terminal caption](https://github.com/DvdGiessen/kwin-toggleterminal/assets/954385/e3f063e7-6fbb-455c-b9bc-15f0cfba6132)

What I do myself is use `tmux` or similar in my foot terminal with the following option in `~/.config/foot/foot.ini:

```ini
shell=/usr/bin/tmux new -As foot
```

Besides the usual advantages of running a multiplexer in foot, it also ensures that the window title always starts with a fixed string (the session name), which can be used for matching the window in `toggle-terminal`.

This seems like a common enough issue that people might run into, so I'll update the README with a similar suggestion.
